version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"

  cloudflared:
    image: cloudflare/cloudflared
    depends_on:
      - app
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run
